# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'unsplash_app' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for unsplash_app  
  pod 'Alamofire'
  pod 'SDWebImage', :modular_headers => true


  target 'unsplash_appTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'unsplash_appUITests' do
    # Pods for testing
  end
  

end


# For CocoaPods after 1.5.0
